// Home
export const GET_HOME_MENUS = 'GET_HOME_MENUS';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const UPDATE_MENU = 'UPDATE_MENU';

// user
export const CHECK_TOKEN = 'READ_COOKIE';
export const SIGNIN = 'SIGNIN';
export const SIGNUP = 'SIGNUP';
export const SIGNOUT = 'SIGNOUT';
export const GET_AUTH_INFO = 'GET_USER_INFO';
export const GET_USER_FROM_STORAGE = 'GET_USER_FROM_STORAGE';
export const UPDATE_CLIENT_USER_INFO = 'UPDATE_CLIENT_USER_INFO';

// utils
export const TOAST = 'TOAST';
export const OPEN_TOAST = 'OPEN_TOAST';
export const CLOSE_TOAST = 'CLOSE_TOAST';


// messageLOGIN
export const GET_UNREAD_MESSAGE_COUNT = 'GET_UNREAD_MESSAGE_COUNT';
export const MARK_AS_READ = 'MARK_AS_READ';
export const GET_MESSAGES_LIST = 'GET_MESSAGES_LIST';


// topic
export const GET_TOPICS_FROM_STORAGE = 'GET_TOPICS_FROM_STORAGE';
export const GET_TOPICS_BY_MENU = 'GET_TOPICS_BY_MENU';
export const UPDATE_TOPICS_BY_MENU = 'UPDATE_TOPICS_BY_MENU';
export const GET_TOPIC_BY_ID = 'GET_TOPIC_BY_ID';
export const REMOVE_TOPIC_CACHE_BY_ID = 'REMOVE_TOPIC_CACHE_BY_ID';
export const REPLY_TOPIC_BY_ID = 'REPLY_TOPIC_BY_ID';
export const UP_REPLY = 'UP_REPLY';
export const PUBLISH = 'PUBLISH';

// reply
export const GET_REPLIES_BY_TOPIC_ID = 'GET_REPLIES_BY_TOPIC_ID';
export const GET_MORE_REPLIES_BY_TOPIC_ID = 'GET_MORE_REPLIES_BY_TOPIC_ID';
export const SUBMIT_REPLY = 'SUBMIT_REPLY';

// middleware
export const SYNC_REDUCER_TO_ASYNC_STORAGE = 'SYNC_REDUCER_TO_ASYNC_STORAGE';
export const GET_REDUCER_FROM_ASYNC_STORAGE = 'GET_REDUCER_FROM_ASYNC_STORAGE';
