export const DB_ERROR = '数据库返回错误'
export const DATA_NOT_FOUND = '数据不存在'
export const DELETED_SUCCESS = '删除成功'
export const REPEAT_DATA = '重复数据'
export const UPDATE_SUCCESS = '更新成功'
export const SAVE_ERROR = '保存成功'
export const PARAMS_ERROR = '参数错误'
export const ACCOUNT_EXIST = '账号已存在'